// Package sonar wraps the SonarQube / SonarCloud sonar-scanner CLI. The gofi
// block `sonar:` in .gofi.yaml is rendered to a sonar-project.properties under
// <project>/.gofi/ every time `gofi sonar` runs; the binary is then invoked
// against it.
//
// The rendered properties scope analysis to first-party project code: only the
// configured source folders are scanned and everything that is not owned by the
// team (tests, mocks, generated code, the vendored SDK under .gofi/, build
// artefacts) is excluded.
package sonar

import (
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/joaoprofile/gofi-cli/internal/config"
)

// ConfigFileName is the path (relative to projectRoot) where gofi writes the
// derived sonar-project.properties before invoking sonar-scanner.
const ConfigFileName = ".gofi/sonar-project.properties"

// property is a single sonar-scanner key/value pair.
type property struct{ key, value string }

// properties derives the ordered sonar-scanner properties from the
// user-friendly SonarConfig. It is the single source of truth shared by the
// rendered .properties file and the -D flags passed to sonar-scanner.
// language selects the language-specific coverage report key (e.g.
// sonar.go.coverage.reportPaths); pass "" when the project has no backend
// language.
func properties(c config.SonarConfig, language string) ([]property, error) {
	if strings.TrimSpace(c.ProjectKey) == "" {
		return nil, errors.New("sonar.project_key is required")
	}

	var props []property
	add := func(k, v string) { props = append(props, property{k, v}) }

	add("sonar.projectKey", c.ProjectKey)
	name := c.ProjectName
	if name == "" {
		name = c.ProjectKey
	}
	add("sonar.projectName", name)
	if c.HostURL != "" {
		add("sonar.host.url", c.HostURL)
	}

	sources := c.Sources
	if len(sources) == 0 {
		sources = []string{"."}
	}
	add("sonar.sources", strings.Join(sources, ","))
	if len(c.Exclusions) > 0 {
		joined := strings.Join(c.Exclusions, ",")
		add("sonar.exclusions", joined)
		// Coverage exclusions mirror analysis exclusions so excluded files
		// never drag the coverage percentage down.
		add("sonar.coverage.exclusions", joined)
	}

	if c.CoverageReport != "" {
		if key := coverageKey(language); key != "" {
			add(key, c.CoverageReport)
		}
	}

	add("sonar.sourceEncoding", "UTF-8")
	return props, nil
}

// BuildProperties derives a sonar-project.properties body from the
// user-friendly SonarConfig. language selects the language-specific coverage
// report key (e.g. sonar.go.coverage.reportPaths); pass "" when the project has
// no backend language.
func BuildProperties(c config.SonarConfig, language string) ([]byte, error) {
	props, err := properties(c, language)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("# Generated by gofi from the sonar: block in .gofi.yaml — do not edit by hand.\n")
	b.WriteString("# Server URL and token come from SONAR_HOST_URL / SONAR_TOKEN in the environment.\n\n")
	for _, p := range props {
		writeProp(&b, p.key, p.value)
	}
	return []byte(b.String()), nil
}

// ScannerArgs renders the derived SonarConfig as -Dkey=value flags for
// sonar-scanner. Passing properties as flags works with both the official Java
// scanner CLI and the npm `sonarqube-scanner` bootstrapper; the latter only
// reads a `sonar-project.properties` from the project base dir and ignores the
// `-Dproject.settings=<file>` flag, so a file-based handoff is not portable.
func ScannerArgs(c config.SonarConfig, language string) ([]string, error) {
	props, err := properties(c, language)
	if err != nil {
		return nil, err
	}
	args := make([]string, 0, len(props))
	for _, p := range props {
		args = append(args, fmt.Sprintf("-D%s=%s", p.key, p.value))
	}
	return args, nil
}

// WriteConfig writes the derived sonar-project.properties into
// <projectRoot>/.gofi/. Returns the absolute path of the written file.
func WriteConfig(projectRoot string, c config.SonarConfig, language string) (string, error) {
	body, err := BuildProperties(c, language)
	if err != nil {
		return "", err
	}
	cfgPath := filepath.Join(projectRoot, ConfigFileName)
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(cfgPath, body, 0o644); err != nil {
		return "", err
	}
	return cfgPath, nil
}

// IsInstalled reports whether the sonar-scanner binary is on PATH.
func IsInstalled() bool {
	_, err := exec.LookPath("sonar-scanner")
	return err == nil
}

// Run invokes `sonar-scanner` from projectRoot with the given -D property
// flags (see ScannerArgs), streaming its stdout/stderr. SONAR_HOST_URL and
// SONAR_TOKEN are inherited from the process environment. Returns the
// underlying exit error; callers should surface non-zero exits (a failed
// quality gate exits non-zero).
func Run(projectRoot string, scannerArgs []string, stdout, stderr io.Writer, stdin io.Reader) error {
	if !IsInstalled() {
		return errors.New("sonar-scanner is not installed; see `gofi sonar install`")
	}
	cmd := exec.Command("sonar-scanner", scannerArgs...)
	cmd.Dir = projectRoot
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	cmd.Stdin = stdin
	return cmd.Run()
}

// coverageKey maps a gofi backend language to the sonar property that points at
// its coverage report. Returns "" for languages gofi has no convention for.
func coverageKey(language string) string {
	switch language {
	case config.LanguageGo:
		return "sonar.go.coverage.reportPaths"
	case config.LanguageRust:
		return "sonar.coverageReportPaths"
	case config.LanguagePython:
		return "sonar.python.coverage.reportPaths"
	case config.LanguageNodeJS:
		return "sonar.javascript.lcov.reportPaths"
	}
	return ""
}

func writeProp(b *strings.Builder, key, value string) {
	fmt.Fprintf(b, "%s=%s\n", key, value)
}
