// Package sonar wraps the SonarQube / SonarCloud sonar-scanner CLI. The gofi
// block `sonar:` in .gofi.yaml is rendered to a sonar-project.properties under
// <project>/.gofi/ every time `gofi sonar` runs; the binary is then invoked
// against it.
//
// The rendered properties scope analysis to first-party project code: only the
// configured source folders are scanned and everything that is not owned by the
// team (tests, mocks, generated code, the vendored SDK under .gofi/, build
// artefacts) is excluded.
package sonar

import (
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/joaoprofile/gofi-cli/internal/config"
)

// ConfigFileName is the path (relative to projectRoot) where gofi writes the
// derived sonar-project.properties before invoking sonar-scanner.
const ConfigFileName = ".gofi/sonar-project.properties"

// BuildProperties derives a sonar-project.properties body from the
// user-friendly SonarConfig. language selects the language-specific coverage
// report key (e.g. sonar.go.coverage.reportPaths); pass "" when the project has
// no backend language.
func BuildProperties(c config.SonarConfig, language string) ([]byte, error) {
	if strings.TrimSpace(c.ProjectKey) == "" {
		return nil, errors.New("sonar.project_key is required")
	}

	var b strings.Builder
	b.WriteString("# Generated by gofi from the sonar: block in .gofi.yaml — do not edit by hand.\n")
	b.WriteString("# Server URL and token come from SONAR_HOST_URL / SONAR_TOKEN in the environment.\n\n")

	writeProp(&b, "sonar.projectKey", c.ProjectKey)
	name := c.ProjectName
	if name == "" {
		name = c.ProjectKey
	}
	writeProp(&b, "sonar.projectName", name)
	if c.HostURL != "" {
		writeProp(&b, "sonar.host.url", c.HostURL)
	}

	sources := c.Sources
	if len(sources) == 0 {
		sources = []string{"."}
	}
	writeProp(&b, "sonar.sources", strings.Join(sources, ","))
	if len(c.Exclusions) > 0 {
		joined := strings.Join(c.Exclusions, ",")
		writeProp(&b, "sonar.exclusions", joined)
		// Coverage exclusions mirror analysis exclusions so excluded files
		// never drag the coverage percentage down.
		writeProp(&b, "sonar.coverage.exclusions", joined)
	}

	if c.CoverageReport != "" {
		if key := coverageKey(language); key != "" {
			writeProp(&b, key, c.CoverageReport)
		}
	}

	writeProp(&b, "sonar.sourceEncoding", "UTF-8")
	return []byte(b.String()), nil
}

// WriteConfig writes the derived sonar-project.properties into
// <projectRoot>/.gofi/. Returns the absolute path of the written file.
func WriteConfig(projectRoot string, c config.SonarConfig, language string) (string, error) {
	body, err := BuildProperties(c, language)
	if err != nil {
		return "", err
	}
	cfgPath := filepath.Join(projectRoot, ConfigFileName)
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(cfgPath, body, 0o644); err != nil {
		return "", err
	}
	return cfgPath, nil
}

// IsInstalled reports whether the sonar-scanner binary is on PATH.
func IsInstalled() bool {
	_, err := exec.LookPath("sonar-scanner")
	return err == nil
}

// Run invokes `sonar-scanner -Dproject.settings=<config>` from projectRoot,
// streaming its stdout/stderr. SONAR_HOST_URL and SONAR_TOKEN are inherited
// from the process environment. Returns the underlying exit error; callers
// should surface non-zero exits (a failed quality gate exits non-zero).
func Run(projectRoot, configPath string, stdout, stderr io.Writer, stdin io.Reader) error {
	if !IsInstalled() {
		return errors.New("sonar-scanner is not installed; see `gofi sonar install`")
	}
	cmd := exec.Command("sonar-scanner", "-Dproject.settings="+configPath)
	cmd.Dir = projectRoot
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	cmd.Stdin = stdin
	return cmd.Run()
}

// MissingEnv returns the SonarQube env vars that are required for a scan but
// absent from the environment, considering an optional host URL pinned in the
// config (which removes the need for SONAR_HOST_URL). Used to warn the user
// before invoking the scanner.
func MissingEnv(hostURLFromConfig string) []string {
	var missing []string
	if os.Getenv("SONAR_TOKEN") == "" {
		missing = append(missing, "SONAR_TOKEN")
	}
	if hostURLFromConfig == "" && os.Getenv("SONAR_HOST_URL") == "" {
		missing = append(missing, "SONAR_HOST_URL")
	}
	return missing
}

// coverageKey maps a gofi backend language to the sonar property that points at
// its coverage report. Returns "" for languages gofi has no convention for.
func coverageKey(language string) string {
	switch language {
	case config.LanguageGo:
		return "sonar.go.coverage.reportPaths"
	case config.LanguageRust:
		return "sonar.coverageReportPaths"
	case config.LanguagePython:
		return "sonar.python.coverage.reportPaths"
	case config.LanguageNodeJS:
		return "sonar.javascript.lcov.reportPaths"
	}
	return ""
}

func writeProp(b *strings.Builder, key, value string) {
	fmt.Fprintf(b, "%s=%s\n", key, value)
}
