package extract

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/importer"
	"go/types"
	"io"
	"maps"
	"os"
	"os/exec"
	"slices"
	"strings"

	"github.com/joaoprofile/gofi-cli/internal/graph/model"
)

// listPkg is the subset of the `go list -json` output we care about.
type listPkg struct {
	ImportPath string
	Dir        string
	Name       string
	Export     string
	Standard   bool
}

// Deep runs the scan with real type-checking. Call edges become exact
// (confidence 1.0) and interface implementations, which fast mode cannot see,
// show up in the graph.
func Deep(opt Options) (*model.Graph, error) {
	s, err := newScanner(opt)
	if err != nil {
		return nil, err
	}
	s.declare()

	imp, warn := s.buildImporter()
	if warn != "" && opt.ShowErrors {
		fmt.Fprintln(os.Stderr, "aviso:", warn)
	}

	checked := map[string]*types.Package{}
	infos := map[string]*types.Info{}

	for _, pkgPath := range s.pkgOrder {
		u := s.pkgs[pkgPath]
		info := &types.Info{
			Defs:       map[*ast.Ident]types.Object{},
			Uses:       map[*ast.Ident]types.Object{},
			Selections: map[*ast.SelectorExpr]*types.Selection{},
		}
		files := make([]*ast.File, 0, len(u.Files))
		for _, pf := range u.Files {
			files = append(files, pf.file)
		}
		conf := types.Config{
			Importer:                 imp,
			Error:                    func(error) {}, // errors do not stop us: we go on with whatever resolved
			DisableUnusedImportCheck: true,
			IgnoreFuncBodies:         false,
		}
		tp, _ := conf.Check(pkgPath, s.fset, files, info)
		if tp != nil {
			checked[pkgPath] = tp
		}
		infos[pkgPath] = info
	}

	s.deepCalls(infos)
	s.deepImplements(checked)
	s.finish()
	return s.g, nil
}

// buildImporter assembles an importer based on the export data generated by
// the go command itself. It is the same mechanism the compiler uses, only with
// no external dependency: everything comes from the standard library.
func (s *scanner) buildImporter() (types.Importer, string) {
	exports, err := goListExports(s.root)
	if err != nil || len(exports) == 0 {
		// Without export data we fall back to the source importer, which is
		// slower but works offline for the standard library.
		return importer.ForCompiler(s.fset, "source", nil),
			"dados de export indisponiveis, usando importador de codigo-fonte"
	}
	src := importer.ForCompiler(s.fset, "source", nil)
	gc := importer.ForCompiler(s.fset, "gc", func(path string) (io.ReadCloser, error) {
		if f, ok := exports[path]; ok && f != "" {
			return os.Open(f)
		}
		return nil, fmt.Errorf("sem dados de export para %q", path)
	})
	return &fallbackImporter{primary: gc, secondary: src, cache: map[string]*types.Package{}}, ""
}

// fallbackImporter tries the export data and, if missing, the source code.
type fallbackImporter struct {
	primary   types.Importer
	secondary types.Importer
	cache     map[string]*types.Package
}

func (f *fallbackImporter) Import(path string) (*types.Package, error) {
	if p, ok := f.cache[path]; ok {
		return p, nil
	}
	if p, err := f.primary.Import(path); err == nil {
		f.cache[path] = p
		return p, nil
	}
	p, err := f.secondary.Import(path)
	if err != nil {
		return nil, err
	}
	f.cache[path] = p
	return p, nil
}

// goListExports asks the go command where the export data of each package is
// (including dependencies and the standard library).
func goListExports(root string) (map[string]string, error) {
	cmd := exec.Command("go", "list", "-e", "-export", "-deps", "-json", "./...")
	cmd.Dir = root
	out, err := cmd.Output()
	if len(out) == 0 {
		if err != nil {
			return nil, err
		}
		return nil, fmt.Errorf("go list nao retornou pacotes")
	}
	res := map[string]string{}
	dec := json.NewDecoder(strings.NewReader(string(out)))
	for {
		var p listPkg
		if err := dec.Decode(&p); err != nil {
			break
		}
		if p.ImportPath != "" && p.Export != "" {
			res[p.ImportPath] = p.Export
		}
	}
	return res, nil
}

// deepCalls rebuilds the call edges using type information.
func (s *scanner) deepCalls(infos map[string]*types.Info) {
	s.unresolved, s.ambiguous, s.extCalls = 0, 0, 0
	for _, pkgPath := range s.pkgOrder {
		u := s.pkgs[pkgPath]
		info := infos[pkgPath]
		if info == nil {
			continue
		}
		for _, pf := range u.Files {
			for _, decl := range pf.file.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok || fd.Body == nil {
					continue
				}
				from := s.declID(pkgPath, fd)
				if from == "" {
					continue
				}
				ast.Inspect(fd.Body, func(n ast.Node) bool {
					call, ok := n.(*ast.CallExpr)
					if !ok {
						return true
					}
					fn := calleeOf(info, call)
					if fn == nil {
						s.unresolved++
						return true
					}
					to := funcID(fn)
					if to == "" {
						s.unresolved++
						return true
					}
					if fn.Pkg() == nil || !s.isInternal(fn.Pkg().Path()) {
						s.extCalls++
						return true
					}
					s.g.AddEdge(&model.Edge{
						From: from, To: to, Rel: model.RelCalls,
						File: pf.src.Rel, Line: s.line(call.Pos()), Conf: 1.0,
					})
					return true
				})
			}
		}
	}
}

// calleeOf figures out exactly which func or method a call invokes.
func calleeOf(info *types.Info, call *ast.CallExpr) *types.Func {
	switch fun := unwrap(call.Fun).(type) {
	case *ast.Ident:
		if obj, ok := info.Uses[fun].(*types.Func); ok {
			return obj
		}
	case *ast.SelectorExpr:
		if sel, ok := info.Selections[fun]; ok && sel != nil {
			if fn, ok := sel.Obj().(*types.Func); ok {
				return fn
			}
		}
		if obj, ok := info.Uses[fun.Sel].(*types.Func); ok {
			return obj
		}
	}
	return nil
}

// funcID translates a type-checker symbol into the canonical graph ID.
func funcID(fn *types.Func) string {
	if fn.Pkg() == nil {
		return ""
	}
	sig, ok := fn.Type().(*types.Signature)
	if ok && sig.Recv() != nil {
		recv := recvName(sig.Recv().Type())
		if recv == "" {
			return ""
		}
		return model.MethodID(fn.Pkg().Path(), recv, fn.Name())
	}
	return model.FuncID(fn.Pkg().Path(), fn.Name())
}

// recvName extracts the receiver type name, ignoring pointers and generics.
func recvName(t types.Type) string {
	switch v := t.(type) {
	case *types.Pointer:
		return recvName(v.Elem())
	case *types.Named:
		return v.Obj().Name()
	case *types.Alias:
		return v.Obj().Name()
	case *types.TypeParam:
		return v.Obj().Name()
	}
	return ""
}

// deepImplements finds out which types satisfy which interfaces. This is the
// information no syntactic heuristic can produce, and it tends to be the most
// useful question to ask about well-decoupled Go code.
func (s *scanner) deepImplements(checked map[string]*types.Package) {
	type named struct {
		id  string
		typ *types.Named
	}
	var concrete []named
	var ifaces []named

	paths := slices.Sorted(maps.Keys(checked))

	for _, p := range paths {
		scope := checked[p].Scope()
		for _, name := range scope.Names() {
			obj, ok := scope.Lookup(name).(*types.TypeName)
			if !ok {
				continue
			}
			n, ok := obj.Type().(*types.Named)
			if !ok {
				continue
			}
			id := model.TypeID(p, name)
			if !s.g.Has(id) {
				continue
			}
			if it, ok := n.Underlying().(*types.Interface); ok {
				if it.NumMethods() > 0 {
					ifaces = append(ifaces, named{id, n})
				}
				continue
			}
			concrete = append(concrete, named{id, n})
		}
	}

	for _, c := range concrete {
		for _, i := range ifaces {
			it, _ := i.typ.Underlying().(*types.Interface)
			if it == nil {
				continue
			}
			if types.Implements(c.typ, it) || types.Implements(types.NewPointer(c.typ), it) {
				n := s.g.Get(c.id)
				e := &model.Edge{From: c.id, To: i.id, Rel: model.RelImplements, Conf: 1.0}
				if n != nil {
					e.File, e.Line = n.File, n.Line
				}
				s.g.AddEdge(e)
			}
		}
	}
}
